name: Update lifts.json

on:
  schedule:
  - cron: '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run
      run: |
        MSG=$(date -Iminutes)
        echo "${{ github.token }}" | docker login https://docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin
        docker run  -v $(pwd):/data docker.pkg.github.com/aaparmeggiani/towerbridge/towerbridge:latest
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A
        git diff-index --quiet HEAD || git commit -m "$MSG"
        git commit -am "$MSG"
        git push
